# set colorscheme
colorscheme gruvbox
# get rid of these italics, they look bad on bitmapped fonts
face global comment rgb:928374

# highlighters
add-highlighter global/ number-lines
add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces

# no clippy
set global ui_options ncurses_assistant=off
# no startup info
set global startup_info_version 99990000

# if not configured per file type, set tabs as 2 spaces
set global tabstop 2

# tab complete
hook global InsertCompletionShow .* %{
    try %{
      execute-keys -draft 'h<a-K>\h<ret>'
      map window insert <tab> <c-n>
      map window insert <s-tab> <c-p>
    }
}

hook global InsertCompletionHide .* %{
  unmap window insert <tab> <c-n>
  unmap window insert <s-tab> <c-p>
}

# leader mode
map global normal <space> , -docstring 'leader'
# clear selections
map global normal <esc> <space> -docstring 'clear selections'


# text objects
map global normal v <a-i>
map global normal V <a-a>

# Typos with writing
define-command W -docstring "miscapped write" %{ write }
define-command Wa -docstring "miscapped write" %{ write-all }
define-command Waq -docstring "miscapped write" %{ write-all-quit }
define-command Wqa -docstring "miscapped write" %{ write-all-quit }


# Install kak plugs
evaluate-commands %sh{
    # kak plugin directory
    PLUGIN_DIRECTORY="$HOME/.kakplugins"
    KAK_PLUG="$PLUGIN_DIRECTORY/plug.kak/rc/plug.kak"

    # if does not exist, create it and git clone kak plug
    if [ -f $KAK_PLUG ]; then
        echo source $KAK_PLUG
    else
        mkdir -p $PLUGIN_DIRECTORY
        echo echo "installing plugins..."
        git clone "https://github.com/andreyorst/plug.kak" "$PLUGIN_DIRECTORY/plug.kak" > /dev/null 
        GIT_RET_CODE=$?
        if [ "$GIT_RET_CODE" -eq "0" ]; then
            echo echo "kak.plug installed successfully"
            echo source $KAK_PLUG
        else
            echo echo "failed to install kak.plug"
        fi
    fi
}

# plugins
set-option global plug_install_dir %sh{ echo $HOME/.kakplugins }
plug "https://github.com/andreyorst/plug.kak" noload
plug "https://github.com/occivink/kakoune-sudo-write"
plug "https://github.com/Delapouite/kakoune-text-objects"
plug "https://github.com/leperdu/kakboard" config %{
    hook global WinCreate .* %{ kakboard-enable }
}
plug "https://github.com/Delapouite/kakoune-i3" config %{
    define-command split -docstring "split along a horizontal line" %{
        i3-new-down
    }

    define-command vsplit -docstring "split along a vertical line" %{
        i3-new-right
    }
    define-command term -docstring "spawn a new zsh terminal" %{
        x11-terminal zsh
        quit
    }
}

# kak-lsp
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable

# C++ and other languages
define-command lsp-restart %{ lsp-stop; lsp-start }
set-option global lsp_completion_trigger "execute-keys 'h<a-h><a-k>\S[^\s,=;*(){}\[\]]\z<ret>'"
set-option global lsp_diagnostic_line_error_sign "!"
set-option global lsp_diagnostic_line_warning_sign "?"
hook global WinSetOption filetype=(c|cpp|rust) %{
    map window user "l" ": enter-user-mode lsp<ret>" -docstring "LSP mode"
    map window lsp "n" "<esc>: lsp-find-error --include-warnings<ret>" -docstring "find next error or warning"
    map window lsp "p" "<esc>: lsp-find-error --previous --include-warnings<ret>" -docstring "find previous error or warning"
    lsp-enable-window
    hook -always global KakEnd .* lsp-exit
    lsp-auto-hover-insert-mode-disable
    set-option window lsp_hover_anchor true
    set-face window DiagnosticError default+u
    set-face window DiagnosticWarning default+u
}
hook global WinSetOption filetype=rust %{
    set-option window lsp_server_configuration rust.clippy_preference="on"
}
