# set colorscheme
# gruvbox theme

colorscheme gruvbox
face global comment rgb:928374

define-command ttygruvbox -docstring "gruvbox colorscheme for tty" %{
        # Code highlighting
        face global value         magenta+b
        face global type          yellow+b
        face global variable      blue+b
        face global module        green+b
        face global function      white+b
        face global string        green+b
        face global keyword       red+b
        face global operator      white+b
        face global attribute     yellow
        face global comment       black+b
        face global documentation comment
        face global meta          cyan
        face global builtin       cyan

        # Markdown highlighting
        face global title     green
        face global header    yellow+b
        face global mono      cyan
        face global block     cyan
        face global link      blue+u
        face global bullet    yellow+b
        face global list      white+b

        face global Default            white,black
        face global PrimarySelection   white,blue+bfg
        face global SecondarySelection black,blue+bfg
        face global PrimaryCursor      black,white+bfg
        face global SecondaryCursor    black,white+bfg
        face global PrimaryCursorEol   black,white+bfg
        face global SecondaryCursorEol black,white+bfg
        face global LineNumbers        black+b
        face global LineNumberCursor   yellow,black+b
        face global LineNumbersWrapped black+b
        face global MenuForeground     magenta,black
        face global MenuBackground     white,black
        face global MenuInfo           white+b
        face global Information        black,white+b
        face global Error              black,red+b
        face global StatusLine         white,black+b
        face global StatusLineMode     yellow+b
        face global StatusLineInfo     magenta+b
        face global StatusLineValue    red+b
        face global StatusCursor       black,white+b
        face global Prompt             yellow+b
        face global MatchingChar       white,magenta+b
        face global BufferPadding      black,black+bfg
        face global Whitespace         black+bf
}

# highlighters
add-highlighter global/ number-lines
add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces

# no clippy
set global ui_options ncurses_assistant=off
# no startup info
set global startup_info_version 99990000

# if not configured per file type, set tabs as 2 spaces
set global tabstop 2

# tab complete
hook global InsertCompletionShow .* %{
    try %{
      execute-keys -draft 'h<a-K>\h<ret>'
      map window insert <tab> <c-n>
      map window insert <s-tab> <c-p>
    }
}

hook global InsertCompletionHide .* %{
  unmap window insert <tab> <c-n>
  unmap window insert <s-tab> <c-p>
}

# leader mode
map global normal <space> , -docstring "leader"
# clear selections
map global normal <esc> <space> -docstring "clear selections"

# text objects selection mode
declare-user-mode sel
map global normal v ":enter-user-mode sel <ret>" -docstring "select object mode"
map global sel i <a-i> -docstring "select inner object"
map global sel a <a-a> -docstring "select outer object"

# Typos with writing
define-command W -docstring "miscapped write" %{ write }
define-command Wa -docstring "miscapped write" %{ write-all }
define-command Waq -docstring "miscapped write" %{ write-all-quit }
define-command Wqa -docstring "miscapped write" %{ write-all-quit }

# Install kak plugs
evaluate-commands %sh{
    # kak plugin directory
    PLUGIN_DIRECTORY="$HOME/.kakplugins"
    KAK_PLUG="$PLUGIN_DIRECTORY/plug.kak/rc/plug.kak"

    # if does not exist, create it and git clone kak plug
    if [ -f $KAK_PLUG ]; then
        echo source $KAK_PLUG
    else
        mkdir -p $PLUGIN_DIRECTORY
        echo echo "installing plugins..."
        git clone "https://github.com/andreyorst/plug.kak" "$PLUGIN_DIRECTORY/plug.kak" > /dev/null 
        GIT_RET_CODE=$?
        if [ "$GIT_RET_CODE" -eq "0" ]; then
            echo echo "kak.plug installed successfully"
            echo source $KAK_PLUG
        else
            echo echo "failed to install kak.plug"
        fi
    fi
}

# plugins
set-option global plug_install_dir %sh{ echo $HOME/.kakplugins }
plug "https://github.com/andreyorst/plug.kak" noload
plug "https://github.com/occivink/kakoune-sudo-write"
plug "https://github.com/delapouite/kakoune-palette"
plug "https://github.com/delapouite/kakoune-text-objects"  config %{
  # disable using % to select file, use vf
  map global normal % nop
}
plug "https://github.com/leperdu/kakboard" config %{
    hook global WinCreate .* %{ kakboard-enable }
}
plug "https://github.com/Delapouite/kakoune-i3" config %{
    define-command split -docstring "split along a horizontal line" %{
        i3-new-down
    }
    define-command vsplit -docstring "split along a vertical line" %{
        i3-new-right
    }
    define-command term -docstring "spawn a new zsh terminal" %{
        x11-terminal zsh
        quit
    }
}

# kak-lsp
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable

# C++ and other languages
define-command lsp-restart %{ lsp-stop; lsp-start }
set-option global lsp_completion_trigger "execute-keys 'h<a-h><a-k>\S[^\s,=;*(){}\[\]]\z<ret>'"
set-option global lsp_diagnostic_line_error_sign "!"
set-option global lsp_diagnostic_line_warning_sign "?"
hook global WinSetOption filetype=(c|cpp|rust|typescript|javascript|python) %{
    map window user "l" ": enter-user-mode lsp<ret>" -docstring "LSP mode"
    map window lsp "n" "<esc>: lsp-find-error --include-warnings<ret>" -docstring "find next error or warning"
    map window lsp "p" "<esc>: lsp-find-error --previous --include-warnings<ret>" -docstring "find previous error or warning"
    hook -always global KakEnd .* lsp-exit
    set-option window lsp_hover_anchor true
    set-face window DiagnosticError default+u
    set-face window DiagnosticWarning default+u
    lsp-enable-window
    lsp-auto-hover-insert-mode-disable
}
hook global WinSetOption filetype=rust %{
    set-option window lsp_server_configuration rust.clippy_preference="on"
}
